[project]
name = "multtestlib"
version = "2022.1"
authors = [
  { name="Ricardo Alvarenga", email="alvarenga.r.ricardo@gmail.com" },
]
description = "Biblioteca para execução de testes de unidade utilizando processamento paralelo."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
